hello/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'home#index' 

  resources :posts do
    member do
      post :toggle_like
    end
  end


  resources :comments do
  end

  resources :users, only: [:index ,:show] do
    member do
      post :toggle_follow
    end

  end
  

  scope module: :front do
    scope module: :users do
      resources :follow_relationships, only: [:create, :destroy] #팔로우/언팔로우시 처리로직 (화면설계 5에 해당)
    end
    scope module: :users do
      resources :top,       only: [:index], as: "top", path: "" # 프로필 페이지TOP(화면설계 1,3,4에해당)
      resources :followers,  only: [:index] # Follower일람 페이지(화면설계 2에해당)
      resources :followings, only: [:index] # Following일람 페이지(화면설계 2에해당)
    end

    namespace :my do
      resources :passwords, only: [:edit, :update]  #비밀번호 변경 기능
      resources  :resigns, only: [:edit, :destroy]    #회원 탈퇴기능
    end

  end

end

hello/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

hello/app/models/comment.rb
class Comment < ApplicationRecord

  paginates_per 5 #page 당 5개의 comment 정의 

  belongs_to :post ,optional:true
  belongs_to :user ,optional:true
    
end

hello/app/models/follow_relationship.rb
class FollowRelationship < ApplicationRecord

    belongs_to :user, optional: :true
    

end

hello/app/models/like.rb
class Like < ApplicationRecord

  belongs_to :user, optional: :true
  belongs_to :post, optional: :true
  
end

hello/app/models/post.rb
class Post < ApplicationRecord

  #paginates_per 10 #page 당 10개의 post 정의 

  belongs_to :user, optional: :true  
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  mount_uploader :avatar, AvatarUploader


  is_impressionable #Make my models impressionable.  조회수 구현

end

hello/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :nullify
  has_many :likes, dependent: :destroy

  has_many :followers, foreign_key: "follower_id", class_name: "FollowRelationship", dependent: :destroy #자신의 id 담기고
  has_many :followings, foreign_key: "following_id", class_name: "FollowRelationship" ,dependent: :destroy #자기를 follow한 사람 id 담김



  #class 명은 대문자로 시작하며, _는 대문자로 구분

  mount_uploader :profile_photo, AvatarUploader

end

hello/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters,
	if: :devise_controller?
  #devise controller와 관련있을 때만 이를 실행한다.
  
  helper_method :resource_name, :resource, :devise_mapping, :resource_class

  def index
    @q = User.ransank(params[:q])
    @users = @q.result(distinct: true)
  end


  def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end

  def resource_class
    User
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
  


  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:phone_number,:profile_photo])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name,:phone_number,:profile_photo])
  end
  #회원가입과 update때 name,phone_number parameter사용


end

hello/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :load_comment, only: [:destroy,:edit,:update]

  # def index
  #   @post = Post.find_by(id: params[:id])
  #   @comments = Comment.find_by(post_id: params[:id])
  # end

  def create
    @comment = Comment.create comment_params
    @comments = @comment.post.comments.order(created_at: :desc)
  end

  def destroy
    @comment.destroy

  end

  def edit
  end

  def update
    @comment.update(comment_params)
  end

  def show
  end
private

  def comment_params
    params.require(:comment).permit(:content,:user_id,:post_id)
  end

  def load_comment
    @comment = Comment.find_by(id: params[:id])
  end

end

hello/app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @posts = Post.order(created_at: :desc).page params[:page]
    @users = User.all
  end    
  
end

hello/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :load_post ,only: [:edit,:update,:show,:destroy]
  before_action :authenticate_user!
  impressionist actions: [:show], :unique => [:impressionable_id, :ip_address]

  def index
    if params[:user_id] 
      @posts = Post.find_by(user_id: params[:user_id]).order(created_at: :desc).page params[:page]
    else
      @posts = Post.order(created_at: :desc).page params[:page]
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create post_params
    redirect_to user_path(current_user.id)
  end

  def show
    @post = Post.find_by(id: params[:id])
    @comments = @post.comments.order(created_at: :desc).page(params[:page]).per(5)

    @post.hit +=1
    @post.save

  end

  def toggle_like
    @like = current_user.likes.find_by(post_id: params[:id])
    @post = Post.find(params[:id])

    if @like
      @like.destroy
    else
      @like = Like.create(post_id: params[:id],user_id: current_user.id)
    end
    
    
  end

  def edit
  end

  def update
    @post.update(post_params)
    redirect_to post_path(@post)
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private

    def load_post
      @post = Post.find_by(id: params[:id])
    end

    def post_params
      params.require(:post).permit(:title,:content,:hit,:user_id,:avatar)
    end

end

hello/app/controllers/search_controller.rb
class SearchController < ApplicationController
end

hello/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user ,only: [:show,:toggle_follow]

  def index
  
    # @q = User.ransack(email: params[:q])
    # puts @q
    # @users = @q.result(distinct: true)
    
    @users = User.select("*").from("users").where("email LIKE :query", query: "#{params[:q] <<"%"}")
    if !(@users.exists?) 
      @users = User.select("*").from("users").where("user_name LIKE :query", query: "#{params[:q] <<"%"}")
    end
    #user의 email 또는 name으로 검색

  end

  def show

    @following = current_user.followings.find_by(follower_id: @user.id)
    if params[:id] 
      @posts = Post.where(user_id: params[:id]).order(created_at: :desc).page params[:page]
    end
  end

  
  def toggle_follow
    
    @following = current_user.followings.find_by(follower_id: @user.id)
    
    if @following
      @following.destroy
    else
      @following = FollowRelationship.create(follower_id: @user.id, following_id: current_user.id)
    end
    render "toggle_follow.js"
    
  end

  private
  def load_user
    @user = User.find_by(id: params[:id])
  end

end

hello/app/helpers/application_helper.rb
module ApplicationHelper
end

hello/app/helpers/comments_helper.rb
module CommentsHelper
end

hello/app/helpers/home_helper.rb
module HomeHelper
end

hello/app/helpers/posts_helper.rb
module PostsHelper
end

hello/app/helpers/search_helper.rb
module SearchHelper
end

hello/app/helpers/users_helper.rb
module UsersHelper
end

hello/app/views/comments/_comment.html.erb
<% comment ||= nil %>
<%if comment %>
  <ol class="row border-bottom p-3" id="ent-<%=comment.id%>" style="font-size:14px;">
    <span style="width:20%"><%= comment.user.email %></span>
    <span style="padding-left:10px;width:70%"><%= comment.content %></span>
    <span class="d-block text-right" style="width:10%">
        <%= link_to "댓글 삭제", comment_path(comment), method: :DELETE,data: { confirm: '정말 삭제하시겠습니까?'}, remote: true, class:"btn btn-primary mb-1" %>
        <%= link_to "댓글 수정", edit_comment_path(comment),remote: true, class:"btn btn-primary"%>
    </span>
  </ol>
<% end %>

hello/app/views/comments/_create.html.erb
<% comment ||= Comment.new %>
<% post ||= nil %>
 <% if post %>
    <div class="mt-5">
    <%=form_for comment, remote: true do |f|  %>
        <div class="row" style="margin-left:0.5px;margin-right:0.3px;">
            <%=f.text_area :content ,placeholder: "댓글을 입력해주세요.",class:"form-control",style: "font-size:10px;width:80%",rows:"5", id:"comment_body"%>
            <%=f.hidden_field :user_id, value: current_user.id %>
            <%=f.hidden_field :post_id, value: post.id%>
            <div class ="row">
            
                <%=f.submit "작성",class:"btn btn-primary",style:"width:20%", id:"comment_submit_btn"%>
            </div>
        </div>
    <%end%>
    </div>
<% end %>

hello/app/views/comments/_edit.html.erb
<% comment ||= nil %>
 <% if comment %>
    <%= form_for comment, remote: true do |c|%>
        <div class="row" style="margin-left:0.5px;margin-right:0.3px;width:480px">
            <%=c.text_area :content ,placeholder: comment.content,class:"form-control",style: "font-size:10px;width:80%",rows:"5", id:"comment_body"%>
            <%=c.submit "수정완료",class:"btn btn-primary",style:"width:20%", id:"comment_submit_btn"%>
        </div>
    <% end %>
 <% end %>

hello/app/views/comments/_index.html.erb
<% comments ||= [] %>
<% if comments&.exists? %>
<br/>
<%# @comments = @post.comments%>
  <ul class="container" style="">
      <% comments.each do |comment|%>
        <%= render 'comments/comment', comment: comment %>
      <%end%>
  </ul>
  

<% end %>

hello/app/views/comments/create.js.erb
 
var comment_list = "<%= j(render(partial: "comments/index", locals: {comments: @comments}))%>"

$('#comments_list').html(comment_list) 

$('#comment_body').val("")

hello/app/views/comments/destroy.js.erb
$("#ent-<%=@comment.id%>").remove()

hello/app/views/comments/edit.js.erb
var edit_form = "<%=j(render(partial: "/comments/edit", locals: {comment: @comment}))%>"
$('#ent-<%=@comment.id%>').html(edit_form)

hello/app/views/comments/update.js.erb
var updatedform = "<%=j(render(partial: "comments/comment", locals: {comment: @comment}))%>"
$('#ent-<%=@comment.id%>').html(updatedform)
$("[id=ent-<%=@comment.id%>]").last().unwrap()

hello/app/views/home/index.html.erb
<div class="container">
  <div>
    <% @users.each do |user|%>
    <%=link_to "#{user.email}프로필", user_path(id: user.id)%>  
    <%end%>
  </div>
  
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">제목</th>
        <th scope="col">작성자</th>
        <th scope="col">조회수</th>
        <th scope="col"> </th>
      </tr>
    </thead>
    <tbody>
      <% @posts.each_with_index do |post, index|%>
      <tr>
        <th scope="row"><%=index + 1%></th>
        <td><%=post.title%></td>
        <% if post.user %>
        <td><%=post.user.email%></td>
        <% else %>
        <td>신원 미상</td>
        <% end %>
        <td><%=post.hit%></td>
        <td><%=link_to "상세보기", post_path(post), class:"btn btn-primary"%></td>
      </tr>
      <%end %>

    </tbody>
  </table>
  <hr/>
  <%= paginate @posts %>
</div>

hello/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'instagram_logo.ico'%>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

  </head>

  <body id="all_body">
    <%=render partial: "shared/header"%>
    
    <main class="container">
      <%= yield %>
    </main>
  </body>
</html>

<style>

#all_body {
  background-color: #FAFAFA; 
}
</style>

hello/app/views/posts/_index.html.erb
<hr/>
<div class="container">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">제목</th>
        <th scope="col">작성자</th>
        <th scope="col">조회수</th>
        <th scope="col"> </th>
      </tr>
    </thead>
    <tbody>
      <% @posts.each_with_index do |post, index|%>
      <tr>
        <th scope="row"><%=index + 1%></th>
        <td><%=post.title%></td>
        <% if post.user %>
        <td><%=post.user.email%></td>
        <% else %>
        <td>신원 미상</td>
        <% end %>
        <td><%=post.hit%></td>
        <td><%=link_to "상세보기", post_path(post), class:"btn btn-primary"%></td>
      </tr>
      <%end %>

    </tbody>
  </table>
  <hr/>
  <%= paginate @posts %>
</div>

hello/app/views/posts/_like_count.html.erb
<span id="<%=post.id%>-like_count" style="padding-right:10px">좋아요수: <%= post.likes.size %></span>

hello/app/views/posts/_toggle_like.html.erb
<% if current_user%>
  <div id="toggle_like">
    <% if current_user.likes.find_by(post_id: post.id).nil? %>
      <%=link_to image_tag("/unlike.png",  width: '40px', height: '23px', border: 'none'), toggle_like_post_path(post.id),method: :POST,remote: true, class:"btn btn-lg btn-secondary"%>
    <% else %>
      <%=link_to image_tag("/like.png", width: '40px', height: '23px', border: 'none'), toggle_like_post_path(post.id),method: :POST,remote: true, class:"btn btn-lg btn-secondary"%>
    <% end %>
  </div>
<%end%>

hello/app/views/posts/edit.html.erb
<div class= "container mt-5" style="font-size:12px">
    <%=form_for @post do |post| %>
        <%=post.label :title%><br/>
        <%=post.text_field :title, placeholder: @post.title ,class:"form-control",style: "font-size:15px"%><br/>
        <%=post.label :content%> <br/>
        <%=post.text_area :content, placehoder: @post.content ,class:"form-control",style: "font-size:15px",cols:"15",rows:"15"%><br/>
        <p style="float:right;margin-right:10px"><%=post.submit "수정완료" , class:"btn btn-lg btn-primary"%></p>
    <%end%>
</div>

hello/app/views/posts/index.html.erb
<hr/>
<div class="container">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">제목</th>
        <th scope="col">작성자</th>
        <th scope="col">조회수</th>
        <th scope="col"> </th>
      </tr>
    </thead>
    <tbody>
      <% @posts.each_with_index do |post, index|%>
      <tr>
        <th scope="row"><%=index + 1%></th>
        <td><%=post.title%></td>
        <% if post.user %>
        <td><%=post.user.email%></td>
        <% else %>
        <td>신원 미상</td>
        <% end %>
        <td><%=post.hit%></td>
        <td><%=link_to "상세보기", post_path(post), class:"btn btn-primary"%></td>
      </tr>
      <%end %>

    </tbody>
  </table>
  <hr/>
  <%= paginate @posts %>
</div>

hello/app/views/posts/new.html.erb
<div class= "container mt-5" style="font-size:12px">
<%= form_for @post do |post| %>
    <%=post.label :title %> <br/>
    <%= post.text_field :title , placeholder: "title" ,class:"form-control",style: "font-size:15px"%> <br/>
    <%= post.label :content %> <br/>
    <%= post.text_area :content ,placeholder: "content",class:"form-control",style: "font-size:15px",cols:"15",rows:"15" %> <br/>
    <%= post.hidden_field :user_id, value: current_user.id %>
    <p style="float:right;margin-right:10px"><%= post.submit "작성완료" , class:"btn btn-primary btn-lg"%></p>
<% end %>
</div>

hello/app/views/posts/show.html.erb
<div class ="container">
  <div class="build" style="background-color:#dbdbdb;margin-top:0px;padding-top:0px">
    <p class="title" style="font-size:30px;padding-bottom:1px;padding-top:0.1px;"><%=@post.title%>
      <span style="float:right;font-size:12px;font-weight:200;padding-top:14px;">
        작성자 : <% if @post.user %> <%= @post.user.email %> <% else %> 신원미상 &nbsp&nbsp<%end%>
        <span style="padding-left:10px;padding-right:10px">조회수 : <%= @post.impressionist_count %></span>
        <%= render partial: 'like_count', locals:{post: @post}%>
      </span>
    </p>
    <hr/>
    <p id = "contents" style="overflow-x:hidden;overflow-y:auto;height:350px;text-align:left;font-size:14px"><%=@post.content %></p>
    <hr/>
    <div class="btn-group btn-lg" role="group" aria-label="Basic example">
      <%= render partial: 'toggle_like', locals: {post: @post}%>
      <% if  (@post.user.nil?) || (@post.user.id == current_user.id)  %>
      <%=link_to "게시글 수정", edit_post_path(@post), method: :GET ,class:"btn btn-lg btn-secondary" %>
      <%=link_to "게시글 삭제", post_path(@post), method: :DELETE, class:"btn btn-lg btn-secondary" %>
      <% end %>
    </div>
    <br/><br/>
  </div>


  <%= render partial: 'comments/create', locals: {post: @post}%>
  <div id="comments_list">
    <%= render partial: 'comments/index', locals: {comments: @comments}%>
  </div>
  <%= paginate @comments, params: {controller: 'posts', action: 'show'} %>


</div>

hello/app/views/posts/toggle_like.js.erb
var like_html = "<%=j(render(partial: "toggle_like", locals:{post: @post}))%>";
var like_count = "<%=j(render(partial: "like_count", locals:{post: @post}))%>"

$('#toggle_like').html(like_html);
$('#<%=@post.id%>-like_count').html(like_count);

hello/app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-white ">
<div class = "container header" style="margin-left:150px">
  <div style = "padding-right: 100px">
    <a class="navbar-brand" href="<%= root_path %>" style="padding-top: 16px;font-size:15px">
      <img src="/instagram/instagram_header.png" width="103" height="29" alt="" loading="lazy">
    </a>
  </div>
  <%# <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button> %>

  <div class="collapse navbar-collapse" id="navbarNav" style="font-size:13px">
    <div style = "padding-left : 100px; padding-right : 100px;">
      <%# <form class="form-inline search-form">
        <input class="form-control mr-sm-2" type="search" placeholder="@Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form> %>
      <%= form_with(url: users_path, method: "get", local: true) do %>
        <%= label_tag(:q, "Search for")%>
        <%= text_field_tag(:q) %>
        <%= submit_tag("Search")%>
      <% end %>
      <%#= @q|= User.new %>
      <%#= search_form_for @q, url: users_path, html: {method: :get} do |f| %>
        <%#= f.label :Search %>
        <%#= f.search_field :user_name_or_email%>
        <%#= f.submit "Search" %>
      <%#end %>
    </div>
    <ul class="navbar-nav" style="padding-left : 100px">
      <li class="nav-item active">
        <a class="nav-link" href="<%= root_path %>">
          <img src="/instagram/instagram_home.png" width = "25" height = "25" alt="home">
          <span class="sr-only">(current)</span>
        </a>
      </li>
      <% if current_user %>
        <li class="nav-item">
          <a class="nav-link" href="<%= root_path %>">
            <img src="/instagram/instagram_message_icon.png"  width = "25" height = "25" alt="메세지">
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= root_path %>">
            <img src="/instagram/instagram_compass_icon.png" width = "25" height = "25" alt="찾기?">
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= root_path %>">
            <img src="/instagram/instagram_heart_off_icon.png"  width = "25" height = "25" alt="좋아요 등 알람">
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= user_path(id: current_user.id)%>">
            <%if current_user.profile_photo.file %>
              <img src="<%= current_user.profile_photo.url%>"  width = "25" height = "25" alt="개인 프로필">
            <%else %>
              <img src="/instagram/instagram_default_profile.png" class="img-responsive img-circle" width = "25" height = "25" alt = "개인 프로필">       
            <%end%>
          </a>
        </li>
        <li class="nav-item" style = "padding-left">
            <%=link_to "로그아웃",  destroy_user_session_path,method: :DELETE ,class:"nav-link" %>
        </li>

      <% else %>
        <li class="nav-item" style = "padding-left">
            <%=link_to "로그인",  new_user_session_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
            <%=link_to "회원가입", new_user_registration_path, class:"nav-link" %> 
        </li>  
      <% end %>
    </ul>
  </div>
</div>
</nav>

<style>

.header {
  display: flex;
  justify-content: space-around;
}

</style>

hello/app/views/users/_follower_count.html.erb
<span id= "<%=@user.id%>-follower_count"><%= @user.followers.size %>  </span>

hello/app/views/users/_toggle_follow.html.erb
<% if current_user.followings.find_by(follower_id: @user.id).nil? %>  
    <% if current_user.followers.find_by(following_id: @user.id).nil? %>
        <%=link_to "팔로우하기", toggle_follow_user_path(@user.id),method: :POST,remote: true, class:"btn btn-lg btn-secondary"%>
    <% else %>
        <%=link_to "맞팔로우하기", toggle_follow_user_path(@user.id),method: :POST,remote: true, class:"btn btn-lg btn-secondary"%>
    <% end %>
<% else %>
    <%=link_to "언팔로우하기", toggle_follow_user_path(@user.id),method: :POST,remote: true, class:"btn btn-lg btn-secondary"%>
<% end %>

hello/app/views/users/index.html.erb
<hr/>
<div class="container">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">email</th>
        <th scope="col">user_name</th>
        <th scope="col"> </th>
      </tr>
    </thead>
    <tbody>
      <% @users.each_with_index do |user, index|%>
      <tr>
        <th scope="row"><%=index + 1%></th>
        <td><%=user.email%></td>
        <td><%=user.user_name%></td>
        <td><%=link_to "프로필가기", user_path(user), class:"btn btn-primary"%></td>
      </tr>
      <%end %>

    </tbody>
  </table>
  <hr/>
</div>

hello/app/views/users/show.html.erb
<% if @user %>
  <div class = "container user_profile">
    <div class = "profile row">
      <div class = "col-md-4 avatar">
        <div class = "wrapper">
          <%if @user.profile_photo.file %>
            <img src="<%= @user.profile_photo.url%>" class = "img-responsive img-cirlcle"  alt="개인 프로필">
          <%else %>
            <img src="/instagram/instagram_default_profile.png" class="img-responsive img-circle" alt = "개인 프로필">       
          <%end%>
        </div>
      
      </div>
      <div class = "col-md-8 basic-info">
        <div class = "user-wrapper">
          <h2 class = "username"> <%= @user.user_name %></h2>
        <%=link_to "Edit Profile", edit_user_registration_path , class: "btn button edit-profile" %>
        </div>
        <ul class="posts">
          <li><span><%= @user.posts.size %></span> posts</li>
          <li><%= render partial:'follower_count'%> followers</li>
          <li><span> <%= @user.followings.size%> </span> followings</li>
        </ul>
        <h2 class="email" ><%=@user.email%></h3>
        <h2 class="phone_number" ><%=@user.phone_number%></h2>
        <% if current_user%>
          <div class="row">
            <div id="toggle_follow">
              <%= render partial: "toggle_follow"%>
            </div>
            <div style="margin-left:5px">
              <%=link_to "메세지보내기",user_path(@user.id),method: :POST,remote: true, class:"btn btn-lg btn-primary"%>
            </div>
            <% if current_user.id == @user.id %>
              <div style="margin-left:5px">
                <%=link_to "게시글 작성", new_post_path, class:"btn btn-lg btn-primary" %>
              </div>
            <%end%>
          </div>
        <%end%>
      </div>
    </div>
  </div>
  <hr/>
  <%= render partial: "posts/index"%>


<% end %>
<style>
ul{
   list-style:none;
   }
</style>

hello/app/views/users/toggle_follow.js.erb
var follow_html = "<%=j(render(partial: "toggle_follow"))%>";
var follower_count = "<%=j(render(partial: "follower_count"))%>"

$('#toggle_follow').html(follow_html);
$('#<%=@user.id%>-follower_count').html(follower_count);